[build]
  publish = "public"  # The directory to publish (if you have any frontend code)
  functions = "functions"  # Directory where the functions are defined

[[redirects]]
  from = "/api/*"  # If you're using /api endpoints for your function routes
  to = "/.netlify/functions/:splat"  # Matches the function name automatically
  status = 200

[[redirects]]
  from = "/*"  # All other requests should redirect to the frontend (in case you have a static front end)
  to = "/index.html"
  status = 200
