[build]
  publish = "public" # The directory to publish
  functions = "netlify/functions" # Directory where the functions are located

[[redirects]]
  from = "/api/*" # Adjusting for friendly route paths
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
