[build]
  publish = "public"  # The directory to publish (if you have any frontend code)
  functions = "functions"  # Directory where the functions are defined

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
